---
- name: Apply nginx config
  template:
    src: nginx.conf.j2
    dest: "/var/lib/docker/volumes/{{ docker_vol }}/_data/nginx.conf"
    owner: root
    group: root
    mode: '644'

- name: Restart nginx container
  docker_container:
    name: "{{ docker_name }}"
    state: started
    restart: yes
- pause:
    prompt: "Waiting 20 seconds for restarting nginx docker container"
    seconds: 20
